### ISSUE TITLE
OOM when calling model.predict(batch_generator(file_valid,2,2))

### ISSUE THREAD

**Issue by dhea1323** [VikasOjha666/MyOwnOCR#1]
the issue I'm having is that I keep getting out of memory issues when i call model.predict but it's fine when i call model.fit to train the data. Running model in Google Colab (GPU).

here's the code :
predict_valid = model.predict(batch_generator(file_valid,2,2))

here's the error message:
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-8-b9e2b74bb811> in <module>()
      1 # Predict validation dataset
----> 2 predict_valid = model.predict(batch_generator(file_valid,2,2))

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57     ctx.ensure_initialized()
     58     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 59                                         inputs, attrs, num_outputs)
     60   except core._NotOkStatusException as e:
     61     if name is not None:

ResourceExhaustedError:  OOM when allocating tensor with shape[2,128,513,513] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model_1/conv2d_43/Relu
 (defined at /usr/local/lib/python3.7/dist-packages/keras/backend.py:4867)
]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_predict_function_1530]

Errors may have originated from an input operation.
Input Source operations connected to node model_1/conv2d_43/Relu:
In[0] model_1/conv2d_43/BiasAdd (defined at /usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py:265)

Operation defined at: (most recent call last)
>>>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>     "__main__", mod_spec)
>>> 
>>>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>>>     exec(code, run_globals)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
>>>     app.launch_new_instance()
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 846, in launch_instance
>>>     app.start()
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
>>>     self.io_loop.start()
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
>>>     self.asyncio_loop.run_forever()
>>> 
>>>   File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
>>>     self._run_once()
>>> 
>>>   File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
>>>     handle._run()
>>> 
>>>   File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
>>>     self._context.run(self._callback, *self._args)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
>>>     handler_func(fileobj, events)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
>>>     self._handle_recv()
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
>>>     self._run_callback(callback, msg)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
>>>     callback(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
>>>     return self.dispatch_shell(stream, msg)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
>>>     handler(stream, idents, msg)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
>>>     user_expressions, allow_stdin)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
>>>     interactivity=interactivity, compiler=compiler, result=result)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
>>>     if self.run_code(code, result):
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
>>>     exec(code_obj, self.user_global_ns, self.user_ns)
>>> 
>>>   File "<ipython-input-8-b9e2b74bb811>", line 2, in <module>
>>>     predict_valid = model.predict(batch_generator(file_valid,2,2))
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1789, in predict
>>>     tmp_batch_outputs = self.predict_function(iterator)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1621, in predict_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1611, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1604, in run_step
>>>     outputs = model.predict_step(data)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1572, in predict_step
>>>     return self(x, training=False)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 452, in call
>>>     inputs, training=training, mask=mask)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py", line 273, in call
>>>     return self.activation(outputs)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/activations.py", line 311, in relu
>>>     return backend.relu(x, alpha=alpha, max_value=max_value, threshold=threshold)
>>> 
>>>   File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 4867, in relu
>>>     x = tf.nn.relu(x)

**Comment by VikasOjha666** [comment]
I hope you are using tensorflow version 1. x and Keras version 2.3 as these were the versions used for the code. Also, you are passing the generator itself. The batch_generator is not a function but a generator that returns two arrays i.e. images and segmentations. Hence you should perform inference in this way.

imgs,segs=next(batch_generator(file_val,2,2))
predict_valid = model.predict(imgs)

The predict_valid is the array of predicted masks and its shape is 2,512,512,1.
It is working for training case as while training both labels and images are needed and the generator is called automatically by the fit function.

**Comment by dhea1323** [comment]
Thank you very much for the explanation. It's helps, I'm still a beginner. I want to ask something else. When detecting text data with other languages, the result is poor. What do I have to do?. If you add new data, which stage of training should be added

here's the image:
![test_image6](https://user-images.githubusercontent.com/37631114/152925347-5ed6889a-f9b7-4ebd-af04-ef38394a48ea.JPG)

and here's the output:
 i case folding
ase folding adalah salah satu bent text preprocegsin yang palin sederhana
dap efektif meskipun sering diabaikan bruja dari cas folding untuk mengubah
semi huru dalam document menial hurt cecil canvas hurufxaj sampan ca
yang diterimaj karate sellir huru dihilangkdl dar dianggap limiter pada
thar inl tidak menggunakal external library papua kit bisa memanfaatkap
model hang tersedia di python
i i
da beberapa cara van apart digunakan dalam taha case folding andd apart
menggunakar beberapa atau menggunakar semuanyc tergantun pada tugs
hang siberian

**Comment by VikasOjha666** [comment]
It seems from the output that the detection is happening well. But still, I would suggest you use the DB model instead of the UNet model to detect the text as mentioned in the improvement section of my article as the DB model is both light and accurate. But still, if your detection is going pretty well and you want to improve the recognition. Then you can try a bunch of different things. One of the obvious things to do is to generate the data in the language you want to recognize. The CRNN model I was training in the repo used the data which was in the English language hence you could write a data generator or find one from the internet which generates the data in the language you want to recognize. Also add more data augmentations like different backgrounds, blurry, lighting conditions,etc. And train on more data. In my example, I was using 150000. Increase that number to 1 million at least and train for a long time. Also as mentioned in the improvement section of my article that the recognition also depends on the font. So make sure the data you are using to train the CRNN model has that font otherwise result will be poor. Lastly, you can do some architectural tuning to get better results. You can also do error analysis to find out where the model is failing and you can include similar examples in your training set and re-train your model.
